### ISSUE TITLE
Multiple Frontend Code Errors!

### ISSUE THREAD

**Issue by samar12-rad** [ayerhssb/Appointment-booking-app#2]
While working with the project, I encountered several errors and inconsistencies in the frontend code that prevent the project from running properly. These include:

Incorrect Syntax for JSON.stringify:

In AuthContext.jsx line 44, JSONstringify is incorrectly used instead of JSON.stringify.
Missing useState Import:

In Doctors.jsx (line 10), the useState hook is used without being imported, causing a ReferenceError: useState is not defined.
General Code Inconsistencies:

Several areas of the code contain inconsistencies, such as improper function definitions or missing imports, which disrupt the normal functioning of the application.
Missing .env File:

The project requires an .env file for environment variables, but it's currently missing. This makes it difficult to start the project properly.
Proposed Solution:

Correct the syntax error for JSON.stringify in AuthContext.jsx.
Import the useState hook from React in Doctors.jsx.
Review the code for additional inconsistencies and apply the necessary fixes to ensure smooth execution.
Include a sample .env file or add instructions for the necessary environment variables in the project documentation.
Question:
Could I be assigned to this issue to help resolve these problems? @ayerhssb

**Comment by AshutoshKumar0206** [comment]
Assign this issue to me. Previously i have worked with react. So i can work on it. I also suffered from these errors before

**Comment by samar12-rad** [comment]
@ayerhssb , can you assign this issue to me, as the solution of this problem is required for further enhancement of the website. I will structurized the whole website by resolving errors in whole code.

**Comment by samar12-rad** [comment]
@ayerhssb, can you pls assign level label ?

**Comment by samar12-rad** [comment]
@ayerhssb . Can you review my pr?
