### ISSUE TITLE
Add `.gitignore` and include necessary files

### ISSUE THREAD

**Issue by naikmubashir** [ayerhssb/Appointment-booking-app#8]
## Description:

To maintain a clean and efficient repository, I propose adding a `.gitignore` file. This will exclude unnecessary files from version control, such as:

- `node_modules`
- `.env`
- `.vscode` or `.DS_Store` 

Including these will help streamline the repository and avoid clutter from irrelevant files.

**Comment by ChandraST12** [comment]
@ayerhssb I can help you to resolve this issue .
 I would be grateful if you could assign me this issue under the GSSoC-ext and Hacktoberfest labels. I am looking forward to working on this issue

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
Can you please add the gssoc-ext label
